Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  AllowedIP:
    Description: IP to allow to access jumbing box
    Type: String
  AMItoUse:
    Description: AMI for jumping box
    Type: String
  KeyName:
    Description: Key name for my jumbing box
    Type: String
# Security Group
Resources:
  JumbingBoxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our test host
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedIP
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  # Server EC2 Instance
  JumbingBox:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AMItoUse
      KeyName: "jumpingbox-key"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: "JumbingBoxSecurityGroup"
          SubnetId:
            Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
Outputs:
  JumpingBoxIP:
    Description: The URL of the ALB
    Value: !GetAtt JumbingBox.PublicIp
